# Generated by Django 5.2.4 on 2025-07-16 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MassEstimationTask',
            fields=[
                ('task_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', '대기 중'), ('processing', '처리 중'), ('completed', '완료'), ('failed', '실패')], default='pending', max_length=20)),
                ('progress', models.FloatField(default=0.0)),
                ('message', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('result_data', models.JSONField(blank=True, null=True)),
                ('estimated_mass', models.FloatField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('ml_task_id', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'mass_estimation_tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
