# Generated by Django 5.2.4 on 2025-07-15 05:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MassEstimationTask',
            fields=[
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('status', models.CharField(choices=[('pending', '대기 중'), ('processing', '처리 중'), ('completed', '완료'), ('failed', '실패')], default='pending', max_length=20)),
                ('progress', models.FloatField(default=0.0)),
                ('message', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('result_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mass_estimation_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100)),
                ('estimated_mass_g', models.FloatField()),
                ('confidence', models.FloatField()),
                ('verification_method', models.CharField(max_length=50)),
                ('reasoning', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='mlserver.massestimationtask')),
            ],
            options={
                'db_table': 'food_items',
            },
        ),
    ]
