# Generated by Django 5.2.4 on 2025-07-16 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlserver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='massestimationtask',
            name='error_message',
            field=models.TextField(blank=True),
        ),
    ]
