# Generated by Django 5.2.4 on 2025-07-16 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlserver', '0002_massestimationtask_error_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='massestimationtask',
            name='error_message',
        ),
    ]
