# Generated by Django 5.2.4 on 2025-07-15 03:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="max_failures",
            field=models.PositiveIntegerField(default=5, verbose_name="최대 실패 가능 횟수"),
        ),
        migrations.AddField(
            model_name="challengeparticipant",
            name="failure_count",
            field=models.PositiveIntegerField(default=0, verbose_name="총 실패 횟수"),
        ),
    ]
