# Generated by Django 5.2.4 on 2025-07-15 03:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0002_challenge_max_failures_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badge",
            name="is_acquired",
            field=models.BooleanField(verbose_name="획득 여부"),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="is_active",
            field=models.BooleanField(verbose_name="활성화 여부"),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="max_failures",
            field=models.PositiveIntegerField(verbose_name="최대 실패 가능 횟수"),
        ),
        migrations.AlterField(
            model_name="challengeparticipant",
            name="current_streak",
            field=models.PositiveIntegerField(verbose_name="현재 연속 성공 횟수"),
        ),
        migrations.AlterField(
            model_name="challengeparticipant",
            name="failure_count",
            field=models.PositiveIntegerField(verbose_name="총 실패 횟수"),
        ),
        migrations.AlterField(
            model_name="challengeparticipant",
            name="max_streak",
            field=models.PositiveIntegerField(verbose_name="최대 연속 성공 횟수"),
        ),
        migrations.AlterField(
            model_name="challengeparticipant",
            name="status",
            field=models.CharField(
                choices=[("survived", "생존"), ("eliminated", "탈락")],
                max_length=10,
                verbose_name="상태",
            ),
        ),
        migrations.AlterField(
            model_name="challengeprogress",
            name="target_achieved",
            field=models.BooleanField(verbose_name="목표 달성 여부"),
        ),
    ]
