# Generated by Django 5.2.4 on 2025-07-15 04:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "challenges",
            "0004_alter_badge_is_acquired_alter_challenge_is_active_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="meal_count",
            field=models.PositiveIntegerField(default=3, verbose_name="하루 식사 횟수"),
        ),
    ]
