# Generated by Django 5.2.4 on 2025-07-15 03:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "challenges",
            "0003_alter_badge_is_acquired_alter_challenge_is_active_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="badge",
            name="is_acquired",
            field=models.BooleanField(default=False, verbose_name="획득 여부"),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="활성화 여부"),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="max_failures",
            field=models.PositiveIntegerField(default=5, verbose_name="최대 실패 가능 횟수"),
        ),
        migrations.AlterField(
            model_name="challengeparticipant",
            name="current_streak",
            field=models.PositiveIntegerField(default=0, verbose_name="현재 연속 성공 횟수"),
        ),
        migrations.AlterField(
            model_name="challengeparticipant",
            name="failure_count",
            field=models.PositiveIntegerField(default=0, verbose_name="총 실패 횟수"),
        ),
        migrations.AlterField(
            model_name="challengeparticipant",
            name="max_streak",
            field=models.PositiveIntegerField(default=0, verbose_name="최대 연속 성공 횟수"),
        ),
        migrations.AlterField(
            model_name="challengeparticipant",
            name="status",
            field=models.CharField(
                choices=[("survived", "생존"), ("eliminated", "탈락")],
                default="survived",
                max_length=10,
                verbose_name="상태",
            ),
        ),
        migrations.AlterField(
            model_name="challengeprogress",
            name="target_achieved",
            field=models.BooleanField(default=False, verbose_name="목표 달성 여부"),
        ),
    ]
